services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - data:/opt/adguardhome/work
      - config:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
    labels:
      tsdproxy.enable: "true"
volumes:
  data:
  config:
