services:
  grafana:
      image: grafana/grafana-oss:latest
      container_name: grafana
      restart: unless-stopped
      networks:
        - monitoring
      ports:
        - 3333:3000
      volumes:
        - data:/var/lib/grafana
      labels:
        tsdproxy.enable: "true"
volumes:
  data:
networks:
  monitoring:
    name: monitoring
