services:
  grafana:
      image: grafana/grafana-oss:latest
      container_name: grafana
      restart: unless-stopped
      networks:
        - monitoring
      ports:
        - 3333:3000
      environment:
        - GF_SERVER_ROOT_URL=${GRAFANA_URL:?}
      volumes:
        - data:/var/lib/grafana
      labels:
        tsdproxy.enable: "true"
  grafana-ntfy:
    image: academo/grafana-ntfy:latest
    container_name: grafana-ntfy
    networks:
      - monitoring
      - ntfy
    command: -ntfy-url=http://ntfy/uptime
volumes:
  data:
networks:
  monitoring:
    name: monitoring
  ntfy:
    name: ntfy
    external: true
