services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - torrents
      - notification
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - config:/config
    ports:
      - 9696:9696
    labels:
      tsdproxy.enable: "true"
volumes:
  config:
networks:
  torrents:
    name: torrents
  notification:
    name: notification
