services:
  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:latest
    container_name: komodo-periphery
    restart: unless-stopped
    networks:
      - komodo_periphery
    ports:
      - 8120:8120
    labels:
      komodo.skip:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ssl-certs:/etc/komodo/ssl
      - repos:/etc/komodo/repos
      - stacks:/etc/komodo/stacks
    environment:
      - PERIPHERY_PASSKEYS=${KOMODO_PASSKEY:?}
      - PERIPHERY_SSL_ENABLED=true
      - PERIPHERY_INCLUDE_DISK_MOUNTS=/etc/hostname
volumes:
  ssl-certs:
  repos:
  stacks:
networks:
  komodo_periphery:
    external: true
