services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - config:/config
      - cache:/cache
      - ${MEDIA_DIR:?}:/media
    environment:
      - PUID=1000
      - PGID=1000
    devices:
      - /dev/dri:/dev/dri
    networks:
      - jellyfin
      - ldap
    ports:
      - 8096:8096
    labels:
      tsdproxy.enable: "true"
volumes:
  config:
  cache:
networks:
  jellyfin:
    name: jellyfin
  ldap:
    external: true
