services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    networks:
      - torrents
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - config:/config
      - ${TORRENTS_DOWNLOAD_DIR:?}:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels:
      tsdproxy.enable: "true"
      tsdproxy.container_port: 9091
volumes:
  config:
networks:
  torrents:
    name: torrents
