services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    volumes:
      - cache:/var/cache/ntfy
      - auth:/var/lib/ntfy
    ports:
      - 8090:80
    environment:
      - NTFY_BASE_URL=${NTFY_URL:?}
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
      - NTFY_AUTH_DEFAULT_ACCESS=write-only
volumes:
  cache:
  auth:
