services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    restart: unless-stopped
    volumes:
      - ${SYNCTHING_SYNC_DIR:?}:/data
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      tsdproxy.enable: "true"
      tsdproxy.container_port: 8384
volumes:
  config:
