services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    restart: unless-stopped
    networks:
      - torrents
      - notification
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${TORRENTS_DOWNLOAD_DIR:?}:/downloads
      - ${MEDIA_DIR:?}:/data
      - config:/config
    ports:
      - 8787:8787
    labels:
      tsdproxy.enable: "true"
volumes:
  config:
networks:
  torrents:
    name: torrents
  notification:
    name: notification
