services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - torrents
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${TORRENTS_DOWNLOAD_DIR:?}:/downloads
      - ${MEDIA_DIR:?}:/data
      - config:/config
    ports:
      - 8989:8989
    labels:
      tsdproxy.enable: "true"
volumes:
  config:
networks:
  torrents:
    external: true
