services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    container_name: loki
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 3100:3100
    volumes:
      - config:/etc/loki
volumes:
  config:
networks:
  monitoring:
    external: true
