services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=debug
    volumes:
      - config:/app/config
    labels:
      tsdproxy.enable: "true"
volumes:
  config:
