services:
  atuin:
    image: ghcr.io/atuinsh/atuin:latest
    container_name: atuin
    restart: unless-stopped
    command: server start
    ports:
      - 8888:8888
    environment:
      ATUIN_HOST: 0.0.0.0
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://${ATUIN_DB_USERNAME:?}:${ATUIN_DB_PASSWORD:?}@db/${ATUIN_DB_NAME:?}
      RUST_LOG: info,atuin_server=debug
    labels:
      tsdproxy.enable: "true"
    depends_on:
      - db
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${ATUIN_DB_NAME:?}
      POSTGRES_USER: ${ATUIN_DB_USERNAME:?}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD:?}
volumes:
  db:
