services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - torrents
      - notification
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ${TORRENTS_DOWNLOAD_DIR:?}:/downloads
      - ${MEDIA_DIR:?}:/data
      - config:/config
    ports:
      - 7878:7878
    labels:
      tsdproxy.enable: "true"
volumes:
  config:
networks:
  torrents:
    external: true
  notification:
    external: true