services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - ${TSDPROXY_CONFIG_DIR:?}:/config
    ports:
      - 9090:8080
volumes:
  data:
