services:
  komga:
    image: gotson/komga
    container_name: komga
    restart: unless-stopped
    volumes:
      - config:/config
      - ${KOMGA_DATA_DIR:?}:/data
      - ${KOMGA_IMPORT_DIR:?}:/import
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 25600:25600
    user: 1000:1000
    labels:
      tsdproxy.enable: "true"
volumes:
  config:
