services:
  core:
    image: ghcr.io/moghtech/komodo:latest
    container_name: komodo-core
    restart: unless-stopped
    labels:
      komodo.skip:
      tsdproxy.enable: "true"
      tsdproxy.name: "komodo"
    depends_on:
      - mongo
    networks:
      - default
      - periphery
    ports:
      - 9120:9120
    environment:
      - KOMODO_DATABASE_ADDRESS=mongo:27017
      - KOMODO_DATABASE_USERNAME=${MONGO_USERNAME:?}
      - KOMODO_DATABASE_PASSWORD=${MONGO_PASSWORD:?}

      - KOMODO_HOST=${KOMODO_URL:?}
      - KOMODO_PASSKEY=${KOMODO_PASSKEY:?}
      - KOMODO_WEBHOOK_SECRET=${KOMODO_WEBHOOK_SECRET:?}
      - KOMODO_JWT_SECRET=${KOMODO_JWT_SECRET:?}

      - KOMODO_LOCAL_AUTH=true
      - KOMODO_DISABLE_USER_REGISTRATION=false
      - KOMODO_ENABLE_NEW_USERS=false
    volumes:
      - repo-cache:/repo-cache
      - ${KOMODO_SYNC_DIR:?}:/syncs
  mongo:
    image: mongo
    container_name: komodo-mongo
    labels:
      komodo.skip:
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:?}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:?}
volumes:
  mongo-data:
  mongo-config:
  repo-cache:
networks:
  default:
  periphery:
