services:
  alloy:
    image: grafana/alloy:latest
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy
    container_name: alloy
    restart: unless-stopped
    privileged: true
    networks:
      - monitoring
    ports:
      - 12345:12345
    volumes:
      - ${ALLOY_CONFIG_DIR:?}:/etc/alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # cAdvisor & docker logs
      - /var/log/journal:/var/log/journal:ro # systemd-journald logs
      - /:/rootfs:ro # cAdvisor & node_exporter
      - /sys:/sys:ro # cAdvisor & node_exporter
      - /run/udev/data:/run/udev/data:ro # node_exporter
      - /var/lib/docker/:/var/lib/docker:ro # cAdvisor
      - /dev/disk/:/dev/disk:ro # cAdvisor
      - /var/run:/var/run:ro # cAdvisor
networks:
  monitoring:
    external: true
