services:
  alloy:
    image: grafana/alloy:latest
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    container_name: alloy
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 12345:12345
    volumes:
      - ${ALLOY_CONFIG:?}:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
  monitoring:
    external: true
