services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    restart: unless-stopped
    networks:
      - default
      - ollama_network
    ports:
      - 3030:3000
    volumes:
      - data:/data/data
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME:?}:${DB_PASSWORD:?}@postgres:5432/${DB_NAME:?}

      - NEXTAUTH_SECRET=${LINKWARDEN_SECRET:?}
      - NEXTAUTH_URL=${LINKWARDEN_URL:?}/api/v1/auth

      - NEXT_PUBLIC_AUTHENTIK_ENABLED=true
      - AUTHENTIK_CUSTOM_NAME=authentik
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER:?}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID:?}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET:?}

      - NEXT_PUBLIC_OLLAMA_ENDPOINT_URL=${OLLAMA_URL:?}
      - OLLAMA_MODEL=${OLLAMA_MODEL:?}
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:?}
      - POSTGRES_USER=${DB_USERNAME:?}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?}
volumes:
  data:
  db:
networks:
  default:
  ollama_network:
    external: true
